### ISSUE TITLE
Can't use command line tool 

### ISSUE THREAD

**Issue by lorrocha** [chrisccerami/ascii-paint#3]
I'm getting this error when trying to run ascii_art start from the command line. Looks like you might've forgotten to declare a dependency?

Looks like the problem is the line 'require 'commander/import''

/Users/lrocha/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- commander/import (LoadError)
    from /Users/lrocha/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in`require'
    from /Users/lrocha/.rvm/gems/ruby-2.1.5/gems/ascii_art-0.3.3/bin/ascii_art:4:in `<top (required)>'
    from /Users/lrocha/.rvm/gems/ruby-2.1.5/bin/ascii_art:23:in`load'
    from /Users/lrocha/.rvm/gems/ruby-2.1.5/bin/ascii_art:23:in `<main>'

**Comment by corincerami** [comment]
That makes sense. It was probably picking up my local install of commander which is why I didn't realize. Thanks for opening the issue.

**Comment by corincerami** [comment]
@lorrocha This issue has been resolved with version 0.3.5 :fireworks: :rainbow:
