### ISSUE TITLE
Curses has been removed from Standard Library

### ISSUE THREAD

**Issue by ghost** [chrisccerami/ascii-paint#4]
Please add runtime dependency to curse ~> 1.0 if Ruby is > 2.1

**Comment by corincerami** [comment]
Thanks for opening the issue. I'll take care of this as soon as I get a chance.

**Comment by corincerami** [comment]
This has been addressed. Thanks again for pointing it out @felipebalbi

**Comment by ghost** [comment]
Hey, no problem. I'll have a look at how you did it. I knew about adding it to gemspec, but didn't know how to add it conditionally on ruby version :-)
